apiVersion: apps/v1
kind: Deployment
metadata:
  name: gas-feeder
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gas-feeder
  template:
    metadata:
      labels:
        app: gas-feeder
    spec:
      containers:
        - name: gas-feeder
          image: uhub.service.ucloud.cn/entropypool/gas-feeder:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/GasFeeder
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: gas-feeder-config
            items:
              - key: service-conf
                path: GasFeeder.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: gas-feeder
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50320
      targetPort: 50320
    - name: grpc
      port: 50321
      targetPort: 50321
    - name: prometheus
      port: 50322
      targetPort: 50322
  selector:
    app: gas-feeder
